# Neo4j Community Edition Deployment for OpenShift/Kubernetes
# This YAML deploys Neo4j 5 Community with APOC plugin
#
# BEFORE DEPLOYING:
# 1. Update the namespace in each resource OR use: oc apply -f neo4j-deployment.yaml -n YOUR_NAMESPACE
# 2. Update the route hosts to match your cluster's apps domain
# 3. Optionally update the storageClassName to match your cluster's storage class
# 4. Update the secret credentials as needed
#
# DEPLOY ORDER:
#   oc apply -f neo4j-deployment.yaml -n YOUR_NAMESPACE
#
# ACCESS:
#   Browser UI: https://neo4j-YOUR_NAMESPACE.apps.YOUR_CLUSTER_DOMAIN
#   Bolt:       neo4j+s://neo4j-bolt-YOUR_NAMESPACE.apps.YOUR_CLUSTER_DOMAIN:443
---
# Secret for Neo4j Authentication
# Format: NEO4J_AUTH should be "username/password"
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  labels:
    app: neo4j
    component: database
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/your-secure-password"      # Change this!
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "your-secure-password"        # Change this!
---
# Persistent Volume Claim for Neo4j Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  labels:
    app: neo4j
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: your-storage-class  # Uncomment and set if not using default
---
# Persistent Volume Claim for Neo4j Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  labels:
    app: neo4j
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: your-storage-class  # Uncomment and set if not using default
---
# Neo4j Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
    component: database
    version: 5-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  strategy:
    type: Recreate  # Important: Neo4j needs Recreate strategy for data consistency
  template:
    metadata:
      labels:
        app: neo4j
        component: database
    spec:
      containers:
        - name: neo4j
          image: neo4j:5-community
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7474
              protocol: TCP
            - name: bolt
              containerPort: 7687
              protocol: TCP
          env:
            # Authentication
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: NEO4J_AUTH
            # Disable strict config validation (useful for container env)
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
            # Enable APOC plugin
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            # Memory Configuration
            - name: NEO4J_server_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_server_memory_heap_max__size
              value: "1G"
            - name: NEO4J_server_memory_pagecache_size
              value: "512m"
            # Network Configuration
            - name: NEO4J_server_default__listen__address
              value: "0.0.0.0"
            - name: NEO4J_server_bolt_enabled
              value: "true"
            - name: NEO4J_server_bolt_listen__address
              value: "0.0.0.0:7687"
            - name: NEO4J_server_http_enabled
              value: "true"
            - name: NEO4J_server_http_listen__address
              value: "0.0.0.0:7474"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
          livenessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-pvc
        - name: neo4j-logs
          persistentVolumeClaim:
            claimName: neo4j-logs-pvc
      terminationGracePeriodSeconds: 30
---
# Service for Neo4j (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
    component: database
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
---
# Route for Neo4j Browser (HTTP UI)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neo4j-browser
  labels:
    app: neo4j
    component: database
spec:
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: neo4j
    weight: 100
  wildcardPolicy: None
---
# Route for Neo4j Bolt Protocol (for client connections)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neo4j-bolt
  labels:
    app: neo4j
    component: database
  annotations:
    haproxy.router.openshift.io/timeout: "60s"
spec:
  port:
    targetPort: bolt
  tls:
    termination: passthrough
  to:
    kind: Service
    name: neo4j
    weight: 100
  wildcardPolicy: None
